"""Add category_id to budgets

Revision ID: 4092c2da2b51
Revises: 16c27455eb84
Create Date: 2026-03-31 16:58:03.344461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4092c2da2b51'
down_revision: Union[str, Sequence[str], None] = '16c27455eb84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'budgets', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.drop_column('budgets', 'category_id')
    # ### end Alembic commands ###
