"""made month int

Revision ID: cd8beb0abb3a
Revises: a3ed474635ee
Create Date: 2026-04-13 15:54:17.215203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd8beb0abb3a'
down_revision: Union[str, Sequence[str], None] = 'a3ed474635ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE budgets
        ALTER COLUMN month TYPE INTEGER
        USING (
            CASE
                WHEN lower(month) = 'january' THEN 1
                WHEN lower(month) = 'february' THEN 2
                WHEN lower(month) = 'march' THEN 3
                WHEN lower(month) = 'april' THEN 4
                WHEN lower(month) = 'may' THEN 5
                WHEN lower(month) = 'june' THEN 6
                WHEN lower(month) = 'july' THEN 7
                WHEN lower(month) = 'august' THEN 8
                WHEN lower(month) = 'september' THEN 9
                WHEN lower(month) = 'october' THEN 10
                WHEN lower(month) = 'november' THEN 11
                WHEN lower(month) = 'december' THEN 12
                ELSE 1
            END
        )
    """) 
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE budgets
        ALTER COLUMN month TYPE VARCHAR
        USING (
            CASE
                WHEN month = 1 THEN 'january'
                WHEN month = 2 THEN 'february'
                WHEN month = 3 THEN 'march'
                WHEN month = 4 THEN 'april'
                WHEN month = 5 THEN 'may'
                WHEN month = 6 THEN 'june'
                WHEN month = 7 THEN 'july'
                WHEN month = 8 THEN 'august'
                WHEN month = 9 THEN 'september'
                WHEN month = 10 THEN 'october'
                WHEN month = 11 THEN 'november'
                WHEN month = 12 THEN 'december'
            END
        )
    """) 
    # ### end Alembic commands ###
